package com.example.demo.dto;


public class RouteDTO {
   
    private Long routeID; 
    // Primary key for Route table, auto-generated by the database
    
    private LoadDTO load;  
    // A Route is always linked to a specific Load (foreign key relationship)

    private String sequenceJSON;  
    // Stores the sequence of stops (with ETA, actions, etc.) as JSON text in a LONGTEXT column

    private Double distanceKm;  
    // Total distance of the route in kilometers

    private Integer estimatedDurationMin;  
    // Estimated duration of the route in minutes

    private Double costEstimate;  
    // Estimated cost for completing the route

    private String status;  
    // Current status of the route (e.g., PLANNED, IN_PROGRESS, COMPLETED)

    // Default constructor
   
    // Getters and setters for all fields
    public Long getRouteID() { return routeID; }
    public void setRouteID(Long routeID) { this.routeID = routeID; }

    public LoadDTO getLoad() { return load; }
    public void setLoad(LoadDTO load) { this.load = load; }

    public String getSequenceJSON() { return sequenceJSON; }
    public void setSequenceJSON(String sequenceJSON) { this.sequenceJSON = sequenceJSON; }

    public Double getDistanceKm() { return distanceKm; }
    public void setDistanceKm(Double distanceKm) { this.distanceKm = distanceKm; }

    public Integer getEstimatedDurationMin() { return estimatedDurationMin; }
    public void setEstimatedDurationMin(Integer estimatedDurationMin) { this.estimatedDurationMin = estimatedDurationMin; }

    public Double getCostEstimate() { return costEstimate; }
    public void setCostEstimate(Double costEstimate) { this.costEstimate = costEstimate; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }
}