package com.example.demo.entity;

import jakarta.persistence.*;

@Entity
public class Route {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long routeID; 
    // Primary key for Route table, auto-generated by the database

    @ManyToOne
    @JoinColumn(name = "loadID", referencedColumnName = "loadID", nullable = false)
    private Load load;  
    // A Route is always linked to a specific Load (foreign key relationship)

    @Lob
    @Column(columnDefinition = "LONGTEXT")
    private String sequenceJSON;  
    // Stores the sequence of stops (with ETA, actions, etc.) as JSON text in a LONGTEXT column

    private Double distanceKm;  
    // Total distance of the route in kilometers

    private Integer estimatedDurationMin;  
    // Estimated duration of the route in minutes

    private Double costEstimate;  
    // Estimated cost for completing the route

    private String status;  
    // Current status of the route (e.g., PLANNED, IN_PROGRESS, COMPLETED)

    // Default constructor
    public Route() {}

    // Getters and setters for all fields
    public Long getRouteID() { return routeID; }
    public void setRouteID(Long routeID) { this.routeID = routeID; }

    public Load getLoad() { return load; }
    public void setLoad(Load load) { this.load = load; }

    public String getSequenceJSON() { return sequenceJSON; }
    public void setSequenceJSON(String sequenceJSON) { this.sequenceJSON = sequenceJSON; }

    public Double getDistanceKm() { return distanceKm; }
    public void setDistanceKm(Double distanceKm) { this.distanceKm = distanceKm; }

    public Integer getEstimatedDurationMin() { return estimatedDurationMin; }
    public void setEstimatedDurationMin(Integer estimatedDurationMin) { this.estimatedDurationMin = estimatedDurationMin; }

    public Double getCostEstimate() { return costEstimate; }
    public void setCostEstimate(Double costEstimate) { this.costEstimate = costEstimate; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }
}