package com.example.demo.entity;

import jakarta.persistence.*;

@Entity
public class RoutingRule {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long ruleID;  
    // Primary key for the RoutingRule table, auto-generated by the database

    private String name;  
    // Name of the routing rule (e.g., "High Priority Pharma Rule")

    @Lob
    @Column(columnDefinition = "LONGTEXT")
    private String conditionsJSON;  
    // Stores rule conditions in JSON format (e.g., origin, destination, commodity type)

    private Integer priority;  
    // Priority level of the rule (higher number = higher precedence)

    private Boolean active;  
    // Indicates whether the rule is currently active (true/false)

    // Default constructor
    public RoutingRule() {}

    // Getters and setters for all fields
    public Long getRuleID() { return ruleID; }
    public void setRuleID(Long ruleID) { this.ruleID = ruleID; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getConditionsJSON() { return conditionsJSON; }
    public void setConditionsJSON(String conditionsJSON) { this.conditionsJSON = conditionsJSON; }

    public Integer getPriority() { return priority; }
    public void setPriority(Integer priority) { this.priority = priority; }

    public Boolean getActive() { return active; }
    public void setActive(Boolean active) { this.active = active; }
}