package com.example.demo.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "shipment_load") // Maps this entity to the "shipment_load" table
public class Load {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long loadID;  
    // Primary key for the Load table, auto-generated by the database

    private String loadCode;  
    // Unique code or identifier for the load

   
    private Long vehicleID;   
    // Each load is assigned to a specific vehicle (foreign key relationship)

    private LocalDateTime plannedStart;  
    // Planned start time for the load

    private LocalDateTime plannedEnd;  
    // Planned end time for the load

    private Double totalWeightKg;  
    // Total weight of all bookings in kilograms

    private Double totalVolumeM3;  
    // Total volume of all bookings in cubic meters

    @Lob
    @Column(columnDefinition = "LONGTEXT")
    private String bookingsJSON;  
    // Stores booking details as a JSON string (large text column)

    private String status;  
    // Current status of the load (e.g., PLANNED, DISPATCHED, COMPLETED)

    // Default constructor
    public Load() {}

	public Long getLoadID() {
		return loadID;
	}

	public void setLoadID(Long loadID) {
		this.loadID = loadID;
	}

	public String getLoadCode() {
		return loadCode;
	}

	public void setLoadCode(String loadCode) {
		this.loadCode = loadCode;
	}

	public Long getVehicleID() {
		return vehicleID;
	}

	public void setVehicleID(Long vehicleID) {
		this.vehicleID = vehicleID;
	}

	public LocalDateTime getPlannedStart() {
		return plannedStart;
	}

	public void setPlannedStart(LocalDateTime plannedStart) {
		this.plannedStart = plannedStart;
	}

	public LocalDateTime getPlannedEnd() {
		return plannedEnd;
	}

	public void setPlannedEnd(LocalDateTime plannedEnd) {
		this.plannedEnd = plannedEnd;
	}

	public Double getTotalWeightKg() {
		return totalWeightKg;
	}

	public void setTotalWeightKg(Double totalWeightKg) {
		this.totalWeightKg = totalWeightKg;
	}

	public Double getTotalVolumeM3() {
		return totalVolumeM3;
	}

	public void setTotalVolumeM3(Double totalVolumeM3) {
		this.totalVolumeM3 = totalVolumeM3;
	}

	public String getBookingsJSON() {
		return bookingsJSON;
	}

	public void setBookingsJSON(String bookingsJSON) {
		this.bookingsJSON = bookingsJSON;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

    // Getters and setters for all fields
    
}