package com.example.demo.dto;
import java.time.LocalDateTime;
import com.example.demo.entities.enums.LoadStatus;
 
public class LoadDTO {
 
	// Primary key for the Load table, auto-generated by the database
    private Long loadID;
 
    // Unique code or identifier for the load
    private String loadCode;  
    
    // Each load is assigned to a specific vehicle (foreign key relationship)
    private VehicleDTO vehicle;   
    
    // Planned start time for the load
    private LocalDateTime plannedStart;  
    
    // Planned end time for the load
    private LocalDateTime plannedEnd;  
 
    // Total weight of all bookings in kilograms
    private Double totalWeightKg;  
 
    // Total volume of all bookings in cubic meters
    private Double totalVolumeM3;  
    
    // Stores booking details as a JSON string (large text column)
    private String bookingsJSON;  
   
 
    // Current status of the load (e.g., PLANNED, DISPATCHED, COMPLETED)
    private LoadStatus status;  


    //Getters and setters
	public Long getLoadID() {
		return loadID;
	}

	public void setLoadID(Long loadID) {
		this.loadID = loadID;
	}

	public String getLoadCode() {
		return loadCode;
	}

	public void setLoadCode(String loadCode) {
		this.loadCode = loadCode;
	}
	
	public VehicleDTO getVehicle() {
		return vehicle;
	}

	public void setVehicle(VehicleDTO vehicle) {
		this.vehicle = vehicle;
	}

	public LocalDateTime getPlannedStart() {
		return plannedStart;
	}

	public void setPlannedStart(LocalDateTime plannedStart) {
		this.plannedStart = plannedStart;
	}

	public LocalDateTime getPlannedEnd() {
		return plannedEnd;
	}

	public void setPlannedEnd(LocalDateTime plannedEnd) {
		this.plannedEnd = plannedEnd;
	}

	public Double getTotalWeightKg() {
		return totalWeightKg;
	}

	public void setTotalWeightKg(Double totalWeightKg) {
		this.totalWeightKg = totalWeightKg;
	}

	public Double getTotalVolumeM3() {
		return totalVolumeM3;
	}

	public void setTotalVolumeM3(Double totalVolumeM3) {
		this.totalVolumeM3 = totalVolumeM3;
	}

	public String getBookingsJSON() {
		return bookingsJSON;
	}

	public void setBookingsJSON(String bookingsJSON) {
		this.bookingsJSON = bookingsJSON;
	}

	public LoadStatus getStatus() {
		return status;
	}

	public void setStatus(LoadStatus status) {
		this.status = status;
	}

}